site_name: "IGCSE CS STUDY powered by CodeRaft"
repo_url: https://github.com/Crisforlove/Algo.git
theme:
  name: 'material'

nav:
  - Home: index.md
  - 1 DATA REPRESENTATION:
      - 1.1 NUMBER SYSTEMS:
          - 1.1.1 WHY COMPUTERS USE BINARY: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.1 WHY COMPUTERS USE BINARY.md
          - 1.1.2 BINARY, HEX AND CONVERTIG BETWEEN NUMBER SYSTEMS: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.2 BINARY, HEX AND CONVERTIG BETWEEN NUMBER SYSTEMS.md
          - 1.1.3 HEXADECIMAL USES: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.3  HEXADECIMAL USES.md
          - 1.1.4 BINARY ADDITION AND OVERFLOW: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.4  BINARY ADDITION AND OVERFLOW
          - 1.1.5 BINARY SHIFT: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.5  BINARY SHIFT.md
          - 1.1.6 TWO'S COMPLEMENT: 1 DATA REPRESENTATION/1.1 NUMBER SYSTEMS/1.1.6  TWO'S COMPLEMENT.md
      - 1.2 TEXT, SOUND AND IMAGES:
          - 1.2.1  TEXT, SOUND AND IMAGES: 1 DATA REPRESENTATION/1.2 TEXT, SOUND AND IMAGES/1.2.1  TEXT, SOUND AND IMAGES.md
          - 1.2.2  SOUND REPRESENTATION: 1 DATA REPRESENTATION/1.2 TEXT, SOUND AND IMAGES/1.2.2  SOUND REPRESENTATION.md
          - 1.2.3  IMAGE REPRESENTATION: 1 DATA REPRESENTATION/1.2 TEXT, SOUND AND IMAGES/1.2.3  IMAGE REPRESENTATION.md
      - 1.3 DATA STORAGE AND COMPRESSION:
          - 1.3.1  DATA STORAGE MEASUREMENTS: 1 DATA REPRESENTATION/1.3 DATA STORAGE AND COMPRESSION/1.3.1  DATA STORAGE MEASUREMENTS.md
          - 1.3.2  CALCULATING FILE SIZE: 1 DATA REPRESENTATION/1.3 DATA STORAGE AND COMPRESSION/1.3.2  CALCULATING FILE SIZE.md


  - 8 Programming:
      - 8.1 PROGRAMMING CONCEPTS: 8 Programming/8.1 PROGRAMMING CONCEPTS.md
      - 8.1(2) PROGRAMMING CONCEPTS: 8 Programming/8.1(2) PROGRAMMING CONCEPTS CONTINUED.md
      - 8.2 ARRAYS: 8 Programming/8.2 ARRAYS.md
      - 8.3 FILE HANDLING: 8 Programming/8.3 FILE HANDLING.md
  - 9 DATABASES:
      - 9.1 DEFINING A DATABASE: 9 DATABASES/9.1  DEFINING A DATABASE.md
      - 9.2  DATA TYPES: 9 DATABASES/9.2  DATA TYPES.md
      - 9.3  PRIMARY KEYS: 9 DATABASES/9.3  PRIMARY KEYS.md
      - 9.4  SQL: 9 DATABASES/9.4  SQL.md
  - 10 BOOLEAN LOGIC:
      - 10.1  LOGIC SYMBOLS AND FUNCTIONS: 10 BOOLEAN LOGIC​ /10.1  LOGIC SYMBOLS AND FUNCTIONS.md
      - 10.2  USING LOGIC GATES: 10 BOOLEAN LOGIC​ /10.2  USING LOGIC GATES.md
  - 0 Memorize:
      - Booklet: 0 Memorize/IGCSE Computer Science Booklet.pdf

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true      # 确保使用 Pygments 进行语法高亮
      linenums: true          # 启用行号
      auto_title: true        # 自动为代码块添加标题
      anchor_linenums: true   # 行号带有锚点，便于链接
  - pymdownx.superfences       # 支持嵌套代码块和内容块
  - pymdownx.inlinehilite      # 支持内联代码块高亮
  - pymdownx.tilde             # 支持 ~~~ 格式的代码块
  - pymdownx.betterem          # 提升 Markdown 中的文本强调效果、

extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-360RS2BYLD
extra:
  google_analytics:
    tracking_id: 'G-360RS2BYLD'
    anonymize_ip: true


